type: AgentSensor
effectors:
  - type: Rigid
    params:
      init_pos: (0.8, 0.8, 0.8)
      init_euler: (0.0, 0.0, 0.0)
      action_dim: 6
      action_scale_p: (1.0, 1.0, 1.0, 1.0, 1.0, 1.0)
      action_scale_v: (1.0, 1.0, 1.0, 1.0, 1.0, 1.0)
    mesh:
      file: plate.obj
      scale: (0.2, 0.2, 0.2)
      euler: (0.0, 0.0, 0.0)
      material: PLATE
      softness: 100.0
    boundary:
      type: cube
      lower: (0, 0.65, 0)
      upper: (0.5, 1, 1)